redisData:
  image: redis
  volumes:
    - /data
  command: echo
redis:
  image: redis
  ports:
    - "6379"
  volumes_from:
    - redisData
memcached:
  image: memcached
  ports:
    - "11211"
postgresData:
  image: postgres
  volumes:
    - /var/lib/postgresql/data
  command: echo
postgres:
  image: postgres
  ports:
    - "5432"
  volumes_from:
    - postgresData
#webpackdevserver:
#  build: .
#  command: webpack-dev-server --config webpack.hot.config.js --hot --progress --inline --port 2998
#  volumes:
#      - .:/app
#  ports:
#    - "2998:2998"
app:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/app
  env_file: .env
  ports:
    - "3000:3000"
  links:
    - redis
    - postgres
    - memcached
    #- webpackdevserver
