default: &default
  adapter: postgresql
  encoding: utf-8
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 25
  username: postgres
  password:
  host: <%= ENV.fetch('POSTGRES_HOST', 'postgres') %>

development:
  <<: *default
  database: urfantasy_dev

test:
  <<: *default
  database: urfantasy_test

production:
  <<: *default
  database: urfantasy_test