@OVERALL_STATS =
  average_deaths: 9.89
  average_kills: 9.84
  average_assists: 9.63

@CHAMPIONS = [
  {key:"Annie", name:"Annie", champion_id:1},
  {key:"Olaf", name:"Olaf", champion_id:2},
  {key:"Galio", name:"Galio", champion_id:3},
  {key:"TwistedFate", name:"Twisted Fate", champion_id:4},
  {key:"XinZhao", name:"Xin Zhao", champion_id:5},
  {key:"Urgot", name:"Urgot", champion_id:6},
  {key:"Leblanc", name:"LeBlanc", champion_id:7},
  {key:"Vladimir", name:"Vladimir", champion_id:8},
  {key:"FiddleSticks", name:"Fiddlesticks", champion_id:9},
  {key:"Kayle", name:"Kayle", champion_id:10},
  {key:"MasterYi", name:"Master Yi", champion_id:11},
  {key:"Alistar", name:"Alistar", champion_id:12},
  {key:"Ryze", name:"Ryze", champion_id:13},
  {key:"Sion", name:"Sion", champion_id:14},
  {key:"Sivir", name:"Sivir", champion_id:15},
  {key:"Soraka", name:"Soraka", champion_id:16},
  {key:"Teemo", name:"Teemo", champion_id:17},
  {key:"Tristana", name:"Tristana", champion_id:18},
  {key:"Warwick", name:"Warwick", champion_id:19},
  {key:"Nunu", name:"Nunu", champion_id:20},
  {key:"MissFortune", name:"Miss Fortune", champion_id:21},
  {key:"Ashe", name:"Ashe", champion_id:22},
  {key:"Tryndamere", name:"Tryndamere", champion_id:23},
  {key:"Jax", name:"Jax", champion_id:24},
  {key:"Morgana", name:"Morgana", champion_id:25},
  {key:"Zilean", name:"Zilean", champion_id:26},
  {key:"Singed", name:"Singed", champion_id:27},
  {key:"Evelynn", name:"Evelynn", champion_id:28},
  {key:"Twitch", name:"Twitch", champion_id:29},
  {key:"Karthus", name:"Karthus", champion_id:30},
  {key:"Chogath", name:"Cho'Gath", champion_id:31},
  {key:"Amumu", name:"Amumu", champion_id:32},
  {key:"Rammus", name:"Rammus", champion_id:33},
  {key:"Anivia", name:"Anivia", champion_id:34},
  {key:"Shaco", name:"Shaco", champion_id:35},
  {key:"DrMundo", name:"Dr. Mundo", champion_id:36},
  {key:"Sona", name:"Sona", champion_id:37},
  {key:"Kassadin", name:"Kassadin", champion_id:38},
  {key:"Irelia", name:"Irelia", champion_id:39},
  {key:"Janna", name:"Janna", champion_id:40},
  {key:"Gangplank", name:"Gangplank", champion_id:41},
  {key:"Corki", name:"Corki", champion_id:42},
  {key:"Karma", name:"Karma", champion_id:43},
  {key:"Taric", name:"Taric", champion_id:44},
  {key:"Veigar", name:"Veigar", champion_id:45},
  {key:"Trundle", name:"Trundle", champion_id:48},
  {key:"Swain", name:"Swain", champion_id:50},
  {key:"Caitlyn", name:"Caitlyn", champion_id:51},
  {key:"Blitzcrank", name:"Blitzcrank", champion_id:53},
  {key:"Malphite", name:"Malphite", champion_id:54},
  {key:"Katarina", name:"Katarina", champion_id:55},
  {key:"Nocturne", name:"Nocturne", champion_id:56},
  {key:"Maokai", name:"Maokai", champion_id:57},
  {key:"Renekton", name:"Renekton", champion_id:58},
  {key:"JarvanIV", name:"Jarvan IV", champion_id:59},
  {key:"Elise", name:"Elise", champion_id:60},
  {key:"Orianna", name:"Orianna", champion_id:61},
  {key:"MonkeyKing", name:"Wukong", champion_id:62},
  {key:"Brand", name:"Brand", champion_id:63},
  {key:"LeeSin", name:"Lee Sin", champion_id:64},
  {key:"Vayne", name:"Vayne", champion_id:67},
  {key:"Rumble", name:"Rumble", champion_id:68},
  {key:"Cassiopeia", name:"Cassiopeia", champion_id:69},
  {key:"Skarner", name:"Skarner", champion_id:72},
  {key:"Heimerdinger", name:"Heimerdinger", champion_id:74},
  {key:"Nasus", name:"Nasus", champion_id:75},
  {key:"Nidalee", name:"Nidalee", champion_id:76},
  {key:"Udyr", name:"Udyr", champion_id:77},
  {key:"Poppy", name:"Poppy", champion_id:78},
  {key:"Gragas", name:"Gragas", champion_id:79},
  {key:"Pantheon", name:"Pantheon", champion_id:80},
  {key:"Ezreal", name:"Ezreal", champion_id:81},
  {key:"Mordekaiser", name:"Mordekaiser", champion_id:82},
  {key:"Yorick", name:"Yorick", champion_id:83},
  {key:"Akali", name:"Akali", champion_id:84},
  {key:"Kennen", name:"Kennen", champion_id:85},
  {key:"Garen", name:"Garen", champion_id:86},
  {key:"Leona", name:"Leona", champion_id:89},
  {key:"Malzahar", name:"Malzahar", champion_id:90},
  {key:"Talon", name:"Talon", champion_id:91},
  {key:"Riven", name:"Riven", champion_id:92},
  {key:"KogMaw", name:"Kog'Maw", champion_id:96},
  {key:"Shen", name:"Shen", champion_id:98},
  {key:"Lux", name:"Lux", champion_id:99},
  {key:"Xerath", name:"Xerath", champion_id:101},
  {key:"Shyvana", name:"Shyvana", champion_id:102},
  {key:"Ahri", name:"Ahri", champion_id:103},
  {key:"Graves", name:"Graves", champion_id:104},
  {key:"Fizz", name:"Fizz", champion_id:105},
  {key:"Volibear", name:"Volibear", champion_id:106},
  {key:"Rengar", name:"Rengar", champion_id:107},
  {key:"Varus", name:"Varus", champion_id:110},
  {key:"Nautilus", name:"Nautilus", champion_id:111},
  {key:"Viktor", name:"Viktor", champion_id:112},
  {key:"Sejuani", name:"Sejuani", champion_id:113},
  {key:"Fiora", name:"Fiora", champion_id:114},
  {key:"Ziggs", name:"Ziggs", champion_id:115},
  {key:"Lulu", name:"Lulu", champion_id:117},
  {key:"Draven", name:"Draven", champion_id:119},
  {key:"Hecarim", name:"Hecarim", champion_id:120},
  {key:"Khazix", name:"Kha'Zix", champion_id:121},
  {key:"Darius", name:"Darius", champion_id:122},
  {key:"Jayce", name:"Jayce", champion_id:126},
  {key:"Lissandra", name:"Lissandra", champion_id:127},
  {key:"Diana", name:"Diana", champion_id:131},
  {key:"Quinn", name:"Quinn", champion_id:133},
  {key:"Syndra", name:"Syndra", champion_id:134},
  {key:"Zyra", name:"Zyra", champion_id:143},
  {key:"Gnar", name:"Gnar", champion_id:150},
  {key:"Zac", name:"Zac", champion_id:154},
  {key:"Yasuo", name:"Yasuo", champion_id:157},
  {key:"Velkoz", name:"Vel'Koz", champion_id:161},
  {key:"Braum", name:"Braum", champion_id:201},
  {key:"Jinx", name:"Jinx", champion_id:222},
  {key:"Lucian", name:"Lucian", champion_id:236},
  {key:"Zed", name:"Zed", champion_id:238},
  {key:"Vi", name:"Vi", champion_id:254},
  {key:"Aatrox", name:"Aatrox", champion_id:266},
  {key:"Nami", name:"Nami", champion_id:267},
  {key:"Azir", name:"Azir", champion_id:268},
  {key:"Thresh", name:"Thresh", champion_id:412},
  {key:"RekSai", name:"Rek'Sai", champion_id:421},
  {key:"Kalista", name:"Kalista", champion_id:429},
  {key:"Bard", name:"Bard", champion_id:432}
]